const ESTIMATE_STATUS = require('../constants/estimate-status');

const EDITABLE_STATUSES = [
  ESTIMATE_STATUS.DRAFT,
  ESTIMATE_STATUS.ZO_REVISION_REQUESTED,
  ESTIMATE_STATUS.HO_REVISION_REQUESTED
];

const SUBMITTABLE_STATUSES = [
  ESTIMATE_STATUS.DRAFT,
  ESTIMATE_STATUS.ZO_REVISION_REQUESTED,
  ESTIMATE_STATUS.HO_REVISION_REQUESTED
];

module.exports = {
  EDITABLE_STATUSES,
  SUBMITTABLE_STATUSES
};
